using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Wires;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Wires.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class WiresMenuUI : FancyWindow
    {
        [Dependency] private IPrototypeManager _prototypeManager = default!;
        [Dependency] private IEntityManager _entityManager = default!;
        [Dependency] private IResourceCache _resourceCache = default!;

        public event Action<int, WiresAction>? OnAction;

        public WiresMenuUI()
        {
            MinSize = SetSize = new Vector2(250, 150);
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
        }

        public void Populate(WiresBoundUserInterfaceState state)
        {

            wiresHBox.RemoveAllChildren();
            var random = new Random(state.WireSeed);
            foreach (var wire in state.WiresList)
            {
                var mirror = random.Next(2) == 0;
                var flip = random.Next(2) == 0;
                var type = random.Next(2);
                var control = new WireControl(wire.Color, wire.Letter, wire.IsCut, flip, mirror, type, _resourceCache)
                {
                    VerticalAlignment = VAlignment.Bottom
                };
                wiresHBox.AddChild(control);

                control.WireClicked += () =>
                {
                    OnAction?.Invoke(wire.Id, wire.IsCut ? WiresAction.Mend : WiresAction.Cut);
                };

                control.ContactsClicked += () =>
                {
                    OnAction?.Invoke(wire.Id, WiresAction.Pulse);
                };
            }

            statusContainer.RemoveAllChildren();

            foreach (var status in state.Statuses)
            {
                if (status.Value is StatusLightData statusLightData)
                {
                    statusContainer.AddChild(new StatusLightUi(statusLightData, _resourceCache));
                }
                else
                {
                    statusContainer.AddChild(new Label
                    {
                        Text = status.ToString()
                    });
                }
            }
        }



    }
}
