using Content.Shared.Chemistry;
using Content.Shared.Storage;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Chemistry.UI;

[GenerateTypedNameReferences]
public sealed partial class ReagentCardControl : Control
{
    public ItemStorageLocation StorageLocation { get; }
    public Action<ItemStorageLocation>? OnPressed;
    public Action<ItemStorageLocation>? OnEjectButtonPressed;

    public ReagentCardControl(ReagentInventoryItem item)
    {
        RobustXamlLoader.Load(this);

        StorageLocation = item.StorageLocation;
        ColorPanel.ModulateSelfOverride = item.ReagentColor;
        ReagentNameLabel.Text = item.ReagentLabel;
        FillLabel.Text = Loc.GetString("reagent-dispenser-window-quantity-label-text", ("quantity", item.Quantity));;


        if (item.Quantity == 0.0)
            MainButton.Disabled = true;

        MainButton.OnPressed += args => OnPressed?.Invoke(StorageLocation);
        EjectButton.OnPressed += args => OnEjectButtonPressed?.Invoke(StorageLocation);
    }
}
