using Content.Client.UserInterface.Tweens;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class TechnologyCardControl : Control
{
    public Action? OnPressed;

    private TechnologyPrototype _proto;

    // INSECURE WARNING!!!
    private bool _playerHasAccess;
    private readonly TweenManager _tweenManager;

    public TechnologyCardControl(TechnologyPrototype technology,
        IPrototypeManager prototypeManager,
        SpriteSystem spriteSys,
        FormattedMessage description,
        int points,
        bool hasAccess,
        TweenManager _manager)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _proto = technology;

        _tweenManager = _manager;
        _playerHasAccess = hasAccess;
        var discipline = prototypeManager.Index<TechDisciplinePrototype>(technology.Discipline);
        Background.ModulateSelfOverride = discipline.Color;

        DisciplineTexture.Texture = spriteSys.Frame0(discipline.Icon);
        TechnologyNameLabel.Text = Loc.GetString(technology.Name);
        var message = new FormattedMessage();
        message.AddMarkupOrThrow(Loc.GetString("research-console-tier-discipline-info",
            ("tier", technology.Tier),
            ("color", discipline.Color),
            ("discipline", Loc.GetString(discipline.Name))));
        TierLabel.SetMessage(message);
        UnlocksLabel.SetMessage(description);
        CostLabel.Text = $"{points}/{_proto.Cost}";

        TechnologyTexture.Texture = spriteSys.Frame0(technology.Icon);

        UpdatePoints(points);

        if (!hasAccess)
            ResearchButton.ToolTip = Loc.GetString("research-console-no-access-popup");

        ResearchButton.OnPressed += _ => OnPressed?.Invoke();
    }

    private void UpdatePoints(float p)
    {
        ResearchButton.Disabled = p < _proto.Cost || !_playerHasAccess;
        var outVal = float.Clamp(p / _proto.Cost, 0, 1);
        CostLabel.Text = $"{p}/{_proto.Cost}";
        ResearchBar.Value = outVal;
    }
}
