using System.Numerics;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Input;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using SixLabors.ImageSharp.ColorSpaces;

namespace Content.Client.UserInterface.Controls.ColorPicker;

/// <summary>
/// An input control for dates.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ColorPicker : FancyWindow
{
    [Dependency] private IInputManager _inputManager = default!;

    public event Action<Color>? OnSaveColors;
    public Color oldColor;
    public Color currentColor;

    public Vector4 currentHsva;

    public ColorPicker(Color color)
    {
        RobustXamlLoader.Load(this);
        oldColor = color;
        currentColor = color;
        currentHsva = Color.ToHsv(color);

        OldColor.ModulateSelfOverride = color;
        NewColor.ModulateSelfOverride = color;

        ColorSweep.OnColorChanged += ColorSweepOnOnColorChanged;
        HexEdit.OnTextEntered += LineEditLinesChanged;

        Red.OnValueChanged += RgbSliderLinesChanged;
        Green.OnValueChanged += RgbSliderLinesChanged;
        Blue.OnValueChanged += RgbSliderLinesChanged;

        Hue.OnValueChanged += HsvSliderLinesChanged;
        Saturation.OnValueChanged += HsvSliderLinesChanged;
        Value.OnValueChanged += HsvSliderLinesChanged;

        hueSweep.OnColorChanged += HueSweepOnOnColorChanged;
        SaveClose.OnPressed += SaveCloseOnOnPressed;
        CloseButton.OnPressed += CloseOnOnPressed;

        Hue.BackgroundStyleBoxOverride = new StyleBoxColorSweep(1);
        Saturation.BackgroundStyleBoxOverride = new StyleBoxColorSweep(2);
        Value.BackgroundStyleBoxOverride = new StyleBoxColorSweep(3);

        Red.BackgroundStyleBoxOverride = new StyleBoxColorSweep(5);
        Green.BackgroundStyleBoxOverride = new StyleBoxColorSweep(6);
        Blue.BackgroundStyleBoxOverride = new StyleBoxColorSweep(7);


        UpdatePreviews();
    }

    private void LineEditLinesChanged(LineEdit.LineEditEventArgs obj)
    {

        if (Color.TryFromHex(HexEdit.Text, out var hexCol))
            return;
        currentColor = hexCol;
        currentHsva = Color.ToHsv(hexCol);
        UpdatePreviews();
    }

    private void HsvSliderLinesChanged(Robust.Client.UserInterface.Controls.Range range)
    {
        var hsvCol = new Vector4(Single.Clamp(Hue.Value / 100, 0.01f, 0.99f),
            Single.Clamp(Saturation.Value / 100, 0, 1),
            Single.Clamp(Value.Value / 100, 0.05f, 1),
            1);
        currentColor = Color.FromHsv(hsvCol);
        currentHsva = hsvCol;
        UpdatePreviews();
    }

    private void RgbSliderLinesChanged(Robust.Client.UserInterface.Controls.Range range)
    {
        var rgbCol = new Vector4(Red.Value / 100, Green.Value / 100, Blue.Value / 100, 1);
        currentColor = new Color(rgbCol);
        currentHsva = Color.ToHsv(new Color(rgbCol));
        UpdatePreviews();
    }

    private void SaveCloseOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        OnSaveColors?.Invoke(currentColor);

        if (!_inputManager.IsKeyDown(Keyboard.Key.Shift))
        {
            Close();
        }
    }

    private void CloseOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
            Close();
    }


    private void ColorSweepOnOnColorChanged(Vector2 outColor)
    {
        var hsvCol = new Vector4(Color.ToHsv(currentColor).X, outColor.X, outColor.Y, 1);
        currentColor = Color.FromHsv(hsvCol);
        currentHsva = hsvCol;
        UpdatePreviews();
    }

    private void HueSweepOnOnColorChanged(float outHue)
    {
        var hsvCol = new Vector4(outHue,
            Color.ToHsv(currentColor).Y,
            Color.ToHsv(currentColor).Z,
            1);
        currentColor = Color.FromHsv(hsvCol);
        currentHsva = hsvCol;
        UpdatePreviews();
    }

    private void UpdatePreviews()
    {
        ColorSweep.SetHueForSweep(Color.FromHsv(currentHsva));
        var hsvCol = currentHsva;
        Hue.SetValueWithoutEvent(float.Clamp(hsvCol.X * 100, 0, 99));
        Saturation.SetValueWithoutEvent(float.Clamp(hsvCol.Y * 100, 0, 99));
        Value.SetValueWithoutEvent(float.Clamp(hsvCol.Z * 100, 5, 99));
        var hsvConvertedToRGB = Color.FromHsv(hsvCol).RGBA;

        Red.SetValueWithoutEvent(hsvConvertedToRGB.X * 100);
        Green.SetValueWithoutEvent(hsvConvertedToRGB.Y * 100);
        Blue.SetValueWithoutEvent(hsvConvertedToRGB.Z * 100);

        var outCol = Color.FromHsv(hsvCol);

        SlidersShaderParameterSet();

        HexEdit.Text = outCol.ToHex();

        NewColor.ModulateSelfOverride = outCol;

        ColorSweep.SetHueForSweep(outCol);

        ColorSweep.ColorWeThinkWeHave = outCol;
    }

    private void SlidersShaderParameterSet()
    {
        Hue.SetValForSweep(currentHsva, 1);
        Saturation.SetValForSweep(currentHsva, 2);
        Value.SetValForSweep(currentHsva, 3);
    }

    public override void Close()
    {
        base.Close();
        ColorSweep.OnColorChanged -= ColorSweepOnOnColorChanged;
    }
}
