using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UIControls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Controls.ColorPicker;

/// <summary>
/// An input control for dates.
/// </summary>
public sealed class ColorPickerSweep : ContainerForkedButton
{

    public event Action<Vector2>? OnColorChanged;

    public Color ColorWeThinkWeHave;

    private Vector2 _selectorPosition;

    public ColorPickerSweep()
    {
        StyleBoxOverride = new StyleBoxColorSweep(4);
        OnPressed += PickColor;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        const float innerRadius = 5f;
        const float outerRadius = 7f;

        var hsvCol = Color.ToHsv(ColorWeThinkWeHave);

        _selectorPosition = new Vector2(hsvCol.Y * PixelWidth, (1-hsvCol.Z) * PixelHeight) ;

        // black outline ring
        handle.DrawCircle(
            _selectorPosition,
            outerRadius,
            Color.Black,
            filled: false
        );

        // white inner ring
        handle.DrawCircle(
            _selectorPosition,
            innerRadius,
            Color.White,
            filled: false
        );
    }



    protected override void Dispose(bool disposing)
    {
        OnPressed -= PickColor;
        base.Dispose(disposing);
    }

    private void PickColor(BaseButton.ButtonEventArgs buttonEventArgs)
    {
        var mousePosRel = UserInterfaceManager.MousePositionScaled.Position - GlobalPosition;
        var mousePercentX = mousePosRel.X / Width;
        var mousePercentY = 1f-(mousePosRel.Y / Height);
        OnColorChanged?.Invoke(new Vector2(mousePercentX, mousePercentY));

    }

    public void SetHueForSweep(Color newColor)
    {
        if (StyleBoxOverride is StyleBoxColorSweep styleBox)
        {
            styleBox.Val = Color.ToHsv(newColor).X;
        }
    }
}
