using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UIControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Controls.ColorPicker;

/// <summary>
/// An input control for dates.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class HueSweep : ContainerForkedButton
{
    public event Action<float>? OnColorChanged;

    public HueSweep()
    {
        RobustXamlLoader.Load(this);
        HueSweepbox.OnPressed += PickColor;
        StyleBoxOverride = new StyleBoxColorSweep(4);
    }

    protected override void Dispose(bool disposing)
    {
        HueSweepbox.OnPressed -= PickColor;
        base.Dispose(disposing);
    }

    private void PickColor(BaseButton.ButtonEventArgs buttonEventArgs)
    {
        var mousePosRel = UserInterfaceManager.MousePositionScaled.Position - HueSweepbox.GlobalPosition;
        var mousePercentX = mousePosRel.X / HueSweepbox.Width;
        OnColorChanged?.Invoke(mousePercentX);
    }

    public void SetHueForSweep(Color newColor)
    {
        if (StyleBoxOverride is StyleBoxColorSweep styleBox)
        {
            styleBox.GetShaderInstance()?.SetParameter("hue", Color.ToHsv(newColor).X);
        }
    }
}
