using Content.Shared.CartridgeLoader;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PDA;

[GenerateTypedNameReferences]
public sealed partial class PdaProgramItem : ContainerButton
{
    private Entity<CartridgeComponent> _cartridge;

    public event Action<EntityUid>? OnProgramItemPressed;
    public event Action<EntityUid>? OnUninstallButtonPressed;
    public event Action<EntityUid>? OnInstallButtonPressed;



    public PdaProgramItem(Entity<CartridgeComponent> program)
    {
        RobustXamlLoader.Load(this);

        SetCartridge(program);

        OnPressed += OnSelfPressed;
        InstallButton.OnPressed += OnInstallPressed;
    }

    private void OnSelfPressed(ButtonEventArgs args)
    {
        OnProgramItemPressed?.Invoke(_cartridge);
    }

    private void OnInstallPressed(ButtonEventArgs args)
    {
        switch (_cartridge.Comp.InstallationStatus)
        {
            case InstallationStatus.Cartridge:
                OnInstallButtonPressed?.Invoke(_cartridge.Owner);
                break;

            case InstallationStatus.Installed:
                OnUninstallButtonPressed?.Invoke(_cartridge.Owner);
                break;

            case InstallationStatus.Readonly:
            default:
                break;
        }
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

    }

    public void SetCartridge(Entity<CartridgeComponent> program)
    {
        // if (program.Comp.Icon is { } icon)
        //     Icon.SetFromSpriteSpecifier(icon);

        _cartridge = program;
        ProgramName.Text = Loc.GetString(program.Comp.ProgramName);

        switch (program.Comp.InstallationStatus)
        {
            case InstallationStatus.Cartridge:
                InstallButton.Visible = true;
                InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-install-button");
                break;
            case InstallationStatus.Installed:
                InstallButton.Visible = true;
                InstallButton.Text = Loc.GetString("cartridge-bound-user-interface-uninstall-button");
                break;
            case InstallationStatus.Readonly:
                InstallButton.Visible = false;
                break;
        }
    }
}
