using Content.Shared.Lathe.Prototypes;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Lathe.UI;

[GenerateTypedNameReferences]
public sealed partial class CategoryControl : Control
{
    public Action<ProtoId<LatheCategoryPrototype>>? OnButtonPressed;

    private ProtoId<LatheCategoryPrototype> _categoryId;
    public ProtoId<LatheCategoryPrototype> CategoryId => _categoryId;

    public CategoryControl(LatheCategoryPrototype categoryProto)
    {
        RobustXamlLoader.Load(this);

        _categoryId = categoryProto.ID;
        CategoryName.Text = Loc.GetString(categoryProto.Name);

        Button.OnPressed += (_) =>
        {
            OnButtonPressed?.Invoke(_categoryId);
        };
    }
}
