using System.Numerics;
using Content.Client.Guidebook;
using Content.Client.Guidebook.Components;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Tweens;
using Content.Client.UserInterface.Tweens.Easers;
using Content.Client.UserInterface.Tweens.Extensions;
using Content.Shared.Guidebook;
using Content.Shared.Stylesheets.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.UserInterface.Controls
{
    [GenerateTypedNameReferences]
    [Virtual]
    public partial class FancyWindow : BaseWindow
    {
        [Dependency] private IEntitySystemManager _sysMan = default!;
        [Dependency] private IEntityManager _entityManager = default!;
        [Dependency] private IStylesheetManager _styleMan = default!;
        private GuidebookSystem? _guidebookSystem;
        private const int DRAG_MARGIN_SIZE = 7;

        public const string StyleClassWindowHelpButton = "windowHelpButton";
        public const string StyleClassWindowCloseButton = "windowCloseButton";

        public FancyWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            CloseButton.OnPressed += _ => Close();
            HelpButton.OnPressed += _ => Help();
            XamlChildren = ContentsContainer.Children;

            BackgroundIcon.Visible = !_hideIcon;
        }

        public string? Title
        {
            get => WindowTitle.Text;
            set => WindowTitle.Text = value;
        }

        private bool _hideIcon = false;
        public bool? HideIcon
        {
            get => _hideIcon;
            set
            {
                if(value != null)
                    _hideIcon = (bool)value;
                BackgroundIcon.Visible = !_hideIcon;
            }
        }

        public new string? Stylesheet
        {
            set
            {
                if (value is null)
                    return;

                if (_styleMan.TryGetStylesheet(value, out var stylesheet))
                    base.Stylesheet = stylesheet;
            }
        }


        /// <summary>
        /// Applies the specified stylesheet from the <see cref="StylesheetComponent"/> on <paramref name="owner"/>.
        /// </summary>
        /// <param name="owner"><see cref="BoundUserInterface.Owner"/></param>
        /// <returns>The stylesheet, if any</returns>
        public string? ApplyStylesheetFrom(EntityUid owner)
        {
            if (!_entityManager.TryGetComponent<StylesheetComponent>(owner, out var stylesheet))
                return null;

            Stylesheet = stylesheet.Stylesheet;
            return stylesheet.Stylesheet;
        }


        private List<ProtoId<GuideEntryPrototype>>? _helpGuidebookIds;

        public List<ProtoId<GuideEntryPrototype>>? HelpGuidebookIds
        {
            get => _helpGuidebookIds;
            set
            {
                _helpGuidebookIds = value;
                HelpButton.Disabled = _helpGuidebookIds == null;
                HelpButton.Visible = !HelpButton.Disabled;
            }
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            if (_entityManager.TrySystem<TweenManager>(out var tweenManager))
            {
                var tween = TweenExtensions.Tween(
                    Color.Transparent,
                    Color.White,
                    v => Modulate = v,
                    0.25f).SetEasing(Easing.OutQuint);

                if (!tween.IsPlaying)
                {
                    tweenManager?.Play(tween);
                }
            }
        }

        protected override void VisibilityChanged(bool newVisible)
        {
            base.VisibilityChanged(newVisible);
            if (newVisible &&_entityManager.TrySystem<TweenManager>(out var tweenManager))
            {
                var tween = TweenExtensions.Tween(
                    Color.Transparent,
                    Color.White,
                    v => Modulate = v,
                    0.15f).SetEasing(Easing.OutQuint);

                if (!tween.IsPlaying)
                {
                    tweenManager?.Play(tween);
                }
            }
        }

        public void Help()
        {
            if (HelpGuidebookIds is null)
                return;
            _guidebookSystem ??= _sysMan.GetEntitySystem<GuidebookSystem>();
            _guidebookSystem.OpenHelp(HelpGuidebookIds);
        }

        protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        {
            var mode = DragMode.Move;

            if (Resizable)
            {
                if (relativeMousePos.Y < DRAG_MARGIN_SIZE)
                {
                    mode = DragMode.Top;
                }
                else if (relativeMousePos.Y > Size.Y - DRAG_MARGIN_SIZE)
                {
                    mode = DragMode.Bottom;
                }

                if (relativeMousePos.X < DRAG_MARGIN_SIZE)
                {
                    mode |= DragMode.Left;
                }
                else if (relativeMousePos.X > Size.X - DRAG_MARGIN_SIZE)
                {
                    mode |= DragMode.Right;
                }
            }

            return mode;
        }

        public string HeaderClass { set => WindowHeader.SetOnlyStyleClass(value); }
        public string TitleClass { set => WindowTitle.SetOnlyStyleClass(value); }
    }

    /// <summary>
    /// Helper functions for working with <see cref="FancyWindow"/>.
    /// </summary>
    public static class FancyWindowExt
    {
        /// <summary>
        /// Sets information for a window (title and guidebooks) based on an entity.
        /// </summary>
        /// <param name="window">The window to modify.</param>
        /// <param name="entityManager">Entity manager used to retrieve the information.</param>
        /// <param name="entity">The entity that this window represents.</param>
        /// <seealso cref="SetTitleFromEntity"/>
        /// <seealso cref="SetGuidebookFromEntity"/>
        public static void SetInfoFromEntity(this FancyWindow window, IEntityManager entityManager, EntityUid entity)
        {
            window.SetTitleFromEntity(entityManager, entity);
            window.SetGuidebookFromEntity(entityManager, entity);
        }

        /// <summary>
        /// Set a window's title to the name of an entity.
        /// </summary>
        /// <param name="window">The window to modify.</param>
        /// <param name="entityManager">Entity manager used to retrieve the information.</param>
        /// <param name="entity">The entity that this window represents.</param>
        /// <seealso cref="SetInfoFromEntity"/>
        public static void SetTitleFromEntity(
            this FancyWindow window,
            IEntityManager entityManager,
            EntityUid entity)
        {
            window.Title = entityManager.GetComponent<MetaDataComponent>(entity).EntityName;
        }

        /// <summary>
        /// Set a window's guidebook IDs to those of an entity.
        /// </summary>
        /// <param name="window">The window to modify.</param>
        /// <param name="entityManager">Entity manager used to retrieve the information.</param>
        /// <param name="entity">The entity that this window represents.</param>
        /// <seealso cref="SetInfoFromEntity"/>
        public static void SetGuidebookFromEntity(
            this FancyWindow window,
            IEntityManager entityManager,
            EntityUid entity)
        {
            window.HelpGuidebookIds = entityManager.GetComponentOrNull<GuideHelpComponent>(entity)?.Guides;
        }
    }
}
