using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class TguiHeader : BoxContainer
{
    public TguiHeader()
    {
        RobustXamlLoader.Load(this);
        XamlChildren = ContentsContainer.Children;
    }

    public string HeaderText
    {
        set => Header.Text = value;
    }
}
