using System.Linq;
using Content.Client.UserInterface;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Shared.Access;
using Content.Shared.Access.Systems;
using Content.Shared.Roles;

namespace Content.Client.Access.UI;

[GenerateTypedNameReferences]
public sealed partial class DepartmentListing : PanelContainer
{
    [Dependency] private ILogManager _logManager = default!;

    private ISawmill _sawmill = default!;

    public Action<AccessLevelPrototype, bool>? JobSelectionUpdated;


    public readonly Dictionary<ProtoId<AccessLevelPrototype>, BaseButton> ButtonsList = new();

    public DepartmentListing()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sawmill = _logManager.GetSawmill("accesslevelcontrol");
    }

    public void Populate(List<JobPrototype> jobs, IPrototypeManager prototypeManager)
    {
        ButtonsList.Clear();
        DepartmentListingEntryHolder.RemoveAllChildren();

        foreach (var job in jobs)
        {
            foreach (var access in job.Access)
            {
                if (!prototypeManager.TryIndex(access, out var accessLevel))
                {
                    _sawmill.Error($"Unable to find accesslevel for {access}");
                    continue;
                }

                if (ButtonsList.ContainsKey(access))
                    continue;

                var newButton = new TguiCheckBox()
                {
                    Text = accessLevel.GetAccessLevelName(),
                    ToggleMode = true,
                    StyleClasses = { "TguiCheckbox" }
                };

                newButton.OnToggled += _ => JobSelectionUpdated?.Invoke(accessLevel, newButton.Pressed);

                ButtonsList.Add(accessLevel.ID, newButton);
                DepartmentListingEntryHolder.AddChild(newButton);
            }
        }
    }

    // reminder that while it's poor design, it's inherited. .pressed is fired off earlier. Where?
    // IDCardconsoleBoundUserInterface.CS
    public void UpdateState(
        List<ProtoId<AccessLevelPrototype>> pressedList,
        List<ProtoId<AccessLevelPrototype>>? enabledList = null)
    {
        foreach (var (accessName, button) in ButtonsList)
        {
            button.Pressed = pressedList.Contains(accessName);
            button.Disabled = !(enabledList?.Contains(accessName) ?? true);
        }
    }
}
