using System.Linq;
using Content.Client.UserInterface;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Tweens;
using Content.Client.UserInterface.Tweens.Builders;
using Content.Client.UserInterface.Tweens.Easers;
using Content.Client.UserInterface.Tweens.Extensions;
using Content.Shared.Access;
using Content.Shared.Access.Systems;
using Content.Shared.CCVar;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using static Content.Shared.Access.Components.IdCardConsoleComponent;

namespace Content.Client.Access.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class IdCardConsoleWindow : FancyWindow
    {
        [Dependency] private IConfigurationManager _cfgManager = default!;
        [Dependency] private IPrototypeManager _prototypeManager = default!;
        [Dependency] private ILogManager _logManager = default!;
        [Dependency] private IEntityManager _entity = default!;

        private readonly ISawmill _logMill = default!;

        private readonly IdCardConsoleBoundUserInterface _owner;

        private IdCardConsoleBoundUserInterfaceState? _internalIDCardState;

        // CCVar.
        private int _maxNameLength;
        private int _maxIdJobLength;

        // private AccessLevelControl _accessButtons = new();
        private readonly List<string> _jobPrototypeIds = new();
        private Dictionary<DepartmentPrototype, List<JobPrototype>> departments;
        private string[] _blacklistedDepartments = ["department-Incarcerated", "department-Silicon"];

        private string? _lastFullName;
        private string? _lastJobTitle;
        private string? _lastJobProto;
        private IDConsoleState _uiState;
        private IDConsoleState? _oldUIState;

        // The job that will be picked if the ID doesn't have a job on the station.
        private static ProtoId<JobPrototype> _defaultJob = "Passenger";

        private DepartmentListing? _departmentContainer;
        private readonly TweenManager? _tweenManager;

        public (DepartmentPrototype, BaseButton) CurrentDepartmentSelected
        {
            get;
            set
            {
                field.Item2?.Pressed = false;
                field = value;
                field.Item2.Pressed = true;
            }
        }

        public IdCardConsoleWindow(IdCardConsoleBoundUserInterface owner,
            IPrototypeManager prototypeManager,
            List<ProtoId<AccessLevelPrototype>> accessLevels)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _logMill = _logManager.GetSawmill(SharedIdCardConsoleSystem.Sawmill);

            _tweenManager = _entity.System<TweenManager>();

            _owner = owner;

            _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);
            _maxIdJobLength = _cfgManager.GetCVar(CCVars.MaxIdJobLength);

            FullNameLineEdit.OnTextEntered += arg2 =>
            {
                _internalIDCardState?.TargetIdName = arg2.Text;
                SubmitDataFromCurrentMenu();
            };
            FullNameLineEdit.IsValid = s => s.Length <= _maxNameLength;

            JobTitleLineEdit.OnTextEntered += arg =>
            {
                _internalIDCardState?.TargetIdJobTitle = arg.Text;
                SubmitDataFromCurrentMenu();
            };
            JobTitleLineEdit.IsValid = s => s.Length <= _maxIdJobLength;

            UpdateUIMenu();

            departments = new Dictionary<DepartmentPrototype, List<JobPrototype>>();

            foreach (var proto in _prototypeManager.EnumeratePrototypes<DepartmentPrototype>())
            {
                var jobList = new List<JobPrototype>();

                foreach (var job in proto.Roles)
                {
                    _prototypeManager.Resolve(job, out JobPrototype? jobPrototype);
                    if (jobPrototype == null)
                        continue;
                    jobList.Add(jobPrototype);
                    _jobPrototypeIds.Add(jobPrototype.ID);
                    JobPresetOptionButton.AddItem(Loc.GetString(jobPrototype.Name), _jobPrototypeIds.Count - 1);
                }

                departments.Add(proto, jobList);
            }

            // Capital! We now have jobs - a bad npc in a game

            foreach (var JobPair in departments)
            {
                if (JobPair.Key.EditorHidden || _blacklistedDepartments.Contains(JobPair.Key.Name))
                    continue;
                var departmentButton = new TguiTabButton(false)
                {
                    Name = $"{JobPair.Key.Name}_button",
                    Text = Loc.GetString(JobPair.Key.Name),
                    StyleClasses = { "categoryButton" },
                };

                departmentButton.OnPressed += button =>
                {
                    CurrentDepartmentSelected = (JobPair.Key, button.Button);
                    RefreshUISelection(prototypeManager);
                };
                CurrentDepartmentSelected = (JobPair.Key, departmentButton);
                DepartmentSelectionHolder.AddChild(departmentButton);
            }


            RefreshUISelection(prototypeManager);

            SelectAllButton.OnPressed += _ =>
            {
                SetAllAccess(true);
                SubmitDataFromCurrentMenu();
            };

            DeselectAllButton.OnPressed += _ =>
            {
                SetAllAccess(false);
                SubmitDataFromCurrentMenu();
            };

            JobPresetOptionButton.OnItemSelected += SelectJobPreset;
        }

        private void RefreshUISelection(IPrototypeManager prototypeManager)
        {
            DepartmentMenuHolder.DisposeAllChildren();
            var selectedDepartment = CurrentDepartmentSelected.Item1;
            var selectedJobList = departments[selectedDepartment];


            // should we add this to a map?
            _departmentContainer = new DepartmentListing()
            {
                Name = selectedDepartment.Name,
                HorizontalExpand = true,
                VerticalExpand = true,
            };

            _departmentContainer.Populate(selectedJobList, prototypeManager);

            if (_internalIDCardState != null)
            {
                _departmentContainer?.UpdateState(_internalIDCardState.TargetIdAccessList?.ToList() ??
                                                  new List<ProtoId<AccessLevelPrototype>>(),
                    _internalIDCardState.AllowedModifyAccessList?.ToList() ??
                    new List<ProtoId<AccessLevelPrototype>>());
            }

            if (_departmentContainer != null)
            {
                DepartmentMenuHolder.AddChild(_departmentContainer);

                _departmentContainer.JobSelectionUpdated += JobSelectionUpdated;
            }
        }

        private void JobSelectionUpdated(AccessLevelPrototype obj, bool selected)
        {
            if (selected)
                _internalIDCardState?.TargetIdAccessList?.Add(obj.ID);
            else
                _internalIDCardState?.TargetIdAccessList?.Remove(obj.ID);

            SubmitDataFromCurrentMenu();
        }

        /// <param name="enabled">If true, every individual access button will be pressed. If false, each will be depressed.</param>
        private void SetAllAccess(bool enabled)
        {
            // foreach (var button in _accessButtons.ButtonsList.Values)
            // {
            //     if (!button.Disabled && button.Pressed != enabled)
            //         button.Pressed = enabled;
            // }
        }

        private void SelectJobPreset(TguiOptionButton.ItemSelectedEventArgs args)
        {
            if (!_prototypeManager.TryIndex(_jobPrototypeIds[args.Id], out JobPrototype? job))
            {
                return;
            }

            JobTitleLineEdit.Text = Loc.GetString(job.Name);
            args.Button.SelectId(args.Id);

            SetAllAccess(false);
            var oldstate = _internalIDCardState;
            // Ugly, but do what we gotta do.
            if (oldstate != null)
            {
                _internalIDCardState = new IdCardConsoleBoundUserInterfaceState(oldstate.IsPrivilegedIdPresent,
                    oldstate.IsPrivilegedIdAuthorized,
                    oldstate.IsTargetIdPresent,
                    oldstate.TargetIdFullName,
                    job.LocalizedName,
                    (List<ProtoId<AccessLevelPrototype>>?)job.Access,
                    oldstate.AllowedModifyAccessList,
                    job,
                    oldstate.PrivilegedIdName,
                    oldstate.TargetIdName);
            }

            SubmitDataFromCurrentMenu();
            RefreshUISelection(_prototypeManager);
        }

        public void RecieveNewID(IdCardConsoleBoundUserInterfaceState state)
        {
            _internalIDCardState = state;
        }

        public void UpdateState(IdCardConsoleBoundUserInterfaceState state)
        {
            RecieveNewID(state);

            PrivilegedIdButton.Text = state.IsPrivilegedIdPresent
                ? Loc.GetString("id-card-console-window-eject-button")
                : Loc.GetString("id-card-console-window-insert-button");

            PrivilegedIdLabel.Text = state.PrivilegedIdName;

            TargetIdButton.Text = state.IsTargetIdPresent
                ? Loc.GetString("id-card-console-window-eject-button")
                : Loc.GetString("id-card-console-window-insert-button");

            TargetIdLabel.Text = state.TargetIdName;

            if (state.IsPrivilegedIdPresent && state.IsPrivilegedIdAuthorized && !state.IsTargetIdPresent)
            {
                _uiState = IDConsoleState.LoggedIn;
                UpdateUIMenu();
            }
            else if (state.IsPrivilegedIdPresent && state.IsPrivilegedIdAuthorized && state.IsTargetIdPresent)
            {
                _uiState = IDConsoleState.IdInserted;
                UpdateUIMenu();
            }
            else
            {
                _uiState = IDConsoleState.On;
                UpdateUIMenu();
            }

            var interfaceEnabled =
                state.IsPrivilegedIdPresent && state.IsPrivilegedIdAuthorized && state.IsTargetIdPresent;

            var fullNameDirty = _lastFullName != null && FullNameLineEdit.Text != state.TargetIdFullName;
            var jobTitleDirty = _lastJobTitle != null && JobTitleLineEdit.Text != state.TargetIdJobTitle;

            FullNameLabel.Modulate = interfaceEnabled ? Color.White : Color.Gray;
            FullNameLineEdit.Editable = interfaceEnabled;
            if (!fullNameDirty)
            {
                FullNameLineEdit.Text = state.TargetIdFullName ?? string.Empty;
            }


            JobTitleLabel.Modulate = interfaceEnabled ? Color.White : Color.Gray;
            JobTitleLineEdit.Editable = interfaceEnabled;
            if (!jobTitleDirty)
            {
                JobTitleLineEdit.Text = state.TargetIdJobTitle ?? string.Empty;
            }

            JobPresetOptionButton.Disabled = !interfaceEnabled;

            var jobIndex = _jobPrototypeIds.IndexOf(state.TargetIdJobPrototype);
            // If the job index is < 0 that means they don't have a job registered in the station records
            // or the IdCardComponent's JobPrototype field.
            // For example, a new ID from a box would have no job index.
            if (jobIndex < 0)
            {
                jobIndex = _jobPrototypeIds.IndexOf(_defaultJob);
            }

            JobPresetOptionButton.SelectId(jobIndex);

            _lastFullName = state.TargetIdFullName;
            _lastJobTitle = state.TargetIdJobTitle;
            _lastJobProto = state.TargetIdJobPrototype;
        }

        private void SubmitDataFromCurrentMenu()
        {
            // Don't send this if it isn't dirty.
            var jobProtoDirty = _lastJobProto != null &&
                                _jobPrototypeIds[JobPresetOptionButton.SelectedId] != _lastJobProto;

            if (_departmentContainer != null && _internalIDCardState != null)
            {
                _owner.SubmitData(
                    _internalIDCardState.TargetIdName,
                    _internalIDCardState.TargetIdJobTitle ?? "Unassigned",
                    // Iterate over the buttons dictionary, filter by `Pressed`, only get key from the key/value pair
                    _internalIDCardState.TargetIdAccessList ?? new List<ProtoId<AccessLevelPrototype>>(),
                    jobProtoDirty ? _jobPrototypeIds[JobPresetOptionButton.SelectedId] : string.Empty);
            }
        }

        #region UI Animations

        private TweenInstance Fade(Color from, Color to)
        {
            return TweenExtensions.Tween(
                    from,
                    to,
                    v => MasterManagerUI.Modulate = v,
                    0.25f)
                .SetEasing(Easing.OutQuint);
        }

        private void PlayTransition(Action showScreen)
        {
            _tweenManager?.Play(
                SequentialTweenInstanceBuilder.New()
                    .Append(Fade(Color.White, Color.Transparent))
                    .AppendCallback(() =>
                    {
                        LoggedInUI.Visible = false;
                        LoginText.Visible = false;
                        EnterIDText.Visible = false;

                        showScreen();
                    })
                    .Append(Fade(Color.Transparent, Color.White))
                    .Build()
            );
        }

        public void UpdateUIMenu()
        {
            if (_oldUIState != null && _oldUIState == _uiState)
            {
                return;
            }

            switch (_uiState)
            {
                case IDConsoleState.On:
                    PlayTransition(ShowLoginScreen);
                    break;

                case IDConsoleState.LoggedIn:
                    PlayTransition(ShowEnterIDScreen);
                    break;

                case IDConsoleState.IdInserted:
                    PlayTransition(ShowIDEditScreen);
                    break;
            }

            _oldUIState = _uiState;
        }

        private void ShowLoginScreen()
        {
            MasterManagerUI.ModulateSelfOverride = Color.Transparent;
            LoginText.Visible = true;
        }

        private void ShowEnterIDScreen()
        {
            MasterManagerUI.ModulateSelfOverride = Color.Transparent;
            EnterIDText.Visible = true;
        }

        private void ShowIDEditScreen()
        {
            MasterManagerUI.ModulateSelfOverride = Color.Transparent;
            LoggedInUI.Visible = true;
        }

        #endregion
    }

    public enum IDConsoleState
    {
        On,
        LoggedIn,
        IdInserted,
    }
}
