using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Tweens;
using Content.Client.UserInterface.Tweens.Builders;
using Content.Client.UserInterface.Tweens.Easers;
using Content.Client.UserInterface.Tweens.Extensions;
using Content.Shared.Atmos;
using Content.Shared.Atmos.Components;
using Content.Shared.Atmos.EntitySystems;
using Content.Shared.Temperature;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Direction = Robust.Shared.Maths.Direction;

namespace Content.Client.Atmos.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class GasAnalyzerWindow : FancyWindow
    {
        private readonly TweenManager? _tweenManager;
        [Dependency] private IEntityManager _entity = default!;
        private readonly SharedAtmosphereSystem _atmosphere;
        private NetEntity _currentEntity = NetEntity.Invalid;


        public GasAnalyzerWindow()
        {
            RobustXamlLoader.Load(this);
            _atmosphere = IoCManager.Resolve<IEntityManager>().System<SharedAtmosphereSystem>();
            _tweenManager = _entity.System<TweenManager>();
            CTabContainer.SetTabVisible(0, false);
            // replace text to loc
            CTabContainer.SetTabTitle(0, "Device");
            CTabContainer.SetTabTitle(1, "Environment");
            CTabContainer.CurrentTab = 1;
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();
            CTabContainer.Modulate = Color.Transparent;
            BootupGasInfo();
        }

        public void Populate(GasAnalyzerUserMessage msg)
        {
            if (msg.NodeGasMixes.Length == 0)
            {
                CTopBox.AddChild(new Label
                {
                    Text = Loc.GetString("gas-analyzer-window-no-data")
                });
                MinSize = new Vector2(CTopBox.DesiredSize.X + 40, MinSize.Y);
                return;
            }

            Vector2 minSize;

            // Environment Tab
            var envMix = msg.NodeGasMixes[0];

            CTabContainer.SetTabVisible(1, true);
            CTabContainer.SetTabTitle(1, envMix.Name);
            CEnvironmentMix.RemoveAllChildren();
            GenerateGasDisplay(envMix, CEnvironmentMix);

            // Device Tab

            CDeviceStack.RemoveAllChildren();

            if (msg.NodeGasMixes.Length > 1)
            {
                if (_currentEntity != msg.DeviceUid)
                {
                    // when we get new device data switch to the device tab
                    CTabContainer.CurrentTab = 0;
                    _currentEntity = msg.DeviceUid;
                }

                CTabContainer.SetTabVisible(0, true);
                CTabContainer.SetTabTitle(0,
                    Loc.GetString("gas-analyzer-window-tab-title-capitalized", ("title", msg.DeviceName)));

                var entity = IoCManager.Resolve<IEntityManager>().GetEntity(msg.DeviceUid);

                if (msg.NodeGasMixes.Length == 0)
                {
                    // Hide device tab, no device selected
                    CTabContainer.SetTabVisible(0, false);
                    CTabContainer.CurrentTab = 1;
                    minSize = new Vector2(CEnvironmentMix.DesiredSize.X + 40, MinSize.Y);
                    _currentEntity = NetEntity.Invalid;
                }

                for (var i = 1; i < msg.NodeGasMixes.Length; i++)
                {
                    AddGasEntry(entity, msg.NodeGasMixes[i]);
                }
            }
        }

        private void AddGasEntry(EntityUid entity, GasMixEntry gasMix)
        {
            var title = Loc.GetString(
                "gas-analyzer-window-tab-title-capitalized",
                ("title", gasMix.Name));

            var entry = new GasAnalyzerEntry(entity, title);

            CDeviceStack.AddChild(entry);
            GenerateGasDisplay(gasMix, entry.Content);
        }

        private void GenerateGasDisplay(GasMixEntry gasMix, Control parent)
        {
            var dataContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical, VerticalExpand = true,
                Margin = new Thickness(4)
            };

            parent.AddChild(dataContainer);

            // Volume label
            var volBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

            volBox.AddChild(new Label
            {
                Text = Loc.GetString("gas-analyzer-window-volume-text"),
                StyleClasses = { StyleClass.LabelSubText },
            });
            volBox.AddChild(new Control
            {
                MinSize = new Vector2(10, 0),
                HorizontalExpand = true
            });
            volBox.AddChild(new Label
            {
                Text = Loc.GetString("gas-analyzer-window-volume-val-text", ("volume", $"{gasMix.Volume:0.##}")),
                Align = Label.AlignMode.Right,
                HorizontalExpand = true,
            });
            dataContainer.AddChild(volBox);

            // Pressure label
            var presBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

            presBox.AddChild(new Label
            {
                Text = Loc.GetString("gas-analyzer-window-pressure-text"),
                StyleClasses = { StyleClass.LabelSubText },
            });
            presBox.AddChild(new Control
            {
                MinSize = new Vector2(10, 0),
                HorizontalExpand = true
            });
            presBox.AddChild(new Label
            {
                Text = Loc.GetString("gas-analyzer-window-pressure-val-text",
                    ("pressure", $"{gasMix.Pressure:0.00}")),
                Align = Label.AlignMode.Right,
                HorizontalExpand = true
            });
            dataContainer.AddChild(presBox);

            // If there is no gas, it doesn't really have a temperature, so skip displaying it
            if (gasMix.Pressure > Atmospherics.GasMinMoles)
            {
                // Temperature label
                var tempBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

                tempBox.AddChild(new Label
                {
                    Text = Loc.GetString("gas-analyzer-window-temperature-text"),
                    StyleClasses = { StyleClass.LabelSubText },
                });
                tempBox.AddChild(new Control
                {
                    MinSize = new Vector2(10, 0),
                    HorizontalExpand = true
                });
                tempBox.AddChild(new Label
                {
                    Text = Loc.GetString("gas-analyzer-window-temperature-val-text",
                        ("tempK", $"{gasMix.Temperature:0.0}"),
                        ("tempC", $"{TemperatureHelpers.KelvinToCelsius(gasMix.Temperature):0.0}")),
                    Align = Label.AlignMode.Right,
                    HorizontalExpand = true
                });
                dataContainer.AddChild(tempBox);
            }

            if (gasMix.Gases == null || gasMix.Gases?.Length == 0)
            {
                // Separator
                dataContainer.AddChild(new Control
                {
                    MinSize = new Vector2(0, 10)
                });

                // Add a label that there are no gases so it's less confusing
                dataContainer.AddChild(new Label
                {
                    Text = Loc.GetString("gas-analyzer-window-no-gas-text"),
                    FontColorOverride = Color.Gray
                });
                // return, everything below is for the fancy gas display stuff
                return;
            }

            // Separator
            dataContainer.AddChild(new Control
            {
                MinSize = new Vector2(0, 10)
            });

            // Add a table with all the gases
            var tableKey = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical
            };
            var tableVal = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical
            };
            var tablePercent = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical
            };
            dataContainer.AddChild(new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Children =
                {
                    tableKey,
                    new Control
                    {
                        MinSize = new Vector2(10, 0),
                        HorizontalExpand = true
                    },
                    tableVal,
                    new Control
                    {
                        MinSize = new Vector2(10, 0),
                        HorizontalExpand = true
                    },
                    tablePercent
                }
            });
            // This is the gas bar thingy
            var height = 30;
            var gasBar = new SegmentedBarChart
            {
                StyleClasses = { SegmentedBarChart.StyleClassClassicSplitBar },
                MinHeight = height,
                MinEntryWidth = 12,
                Gap = 3
            };
            // Separator
            dataContainer.AddChild(new Control
            {
                MinSize = new Vector2(0, 10),
                VerticalExpand = true
            });

            var totalGasAmount = 0f;
            foreach (var gas in gasMix.Gases!)
            {
                totalGasAmount += gas.Amount;
            }

            tableKey.AddChild(new Label
                { Text = Loc.GetString("gas-analyzer-window-gas-column-name"), Align = Label.AlignMode.Center });
            tableVal.AddChild(new Label
            {
                Text = Loc.GetString("gas-analyzer-window-molarity-column-name"), Align = Label.AlignMode.Center
            });
            tablePercent.AddChild(new Label
            {
                Text = Loc.GetString("gas-analyzer-window-percentage-column-name"), Align = Label.AlignMode.Center
            });

            tableKey.AddChild(new StripeBack());
            tableVal.AddChild(new StripeBack());
            tablePercent.AddChild(new StripeBack());

            for (var j = 0; j < gasMix.Gases.Length; j++)
            {
                var gasEntry = gasMix.Gases[j];
                var gasProto = _atmosphere.GetGas(gasEntry.Gas);
                var localizedName = Loc.GetString(gasProto.Name);


                // Add to the table

                tableKey.AddChild(new Label
                {
                    Text = localizedName
                });
                tableVal.AddChild(new Label
                {
                    Text = Loc.GetString("gas-analyzer-window-molarity-text",
                        ("mol", $"{gasEntry.Amount:0.00}")),
                    Align = Label.AlignMode.Right,
                });
                tablePercent.AddChild(new Label
                {
                    Text = Loc.GetString("gas-analyzer-window-percentage-text",
                        ("percentage", $"{(gasEntry.Amount / totalGasAmount * 100):0.0}")),
                    Align = Label.AlignMode.Right
                });

                // Add to the gas bar
                var tooltip = Loc.GetString("gas-analyzer-window-molarity-percentage-text",
                    ("gasName", localizedName),
                    ("amount", $"{gasEntry.Amount:0.##}"),
                    ("percentage", $"{(gasEntry.Amount / totalGasAmount * 100):0.#}"));

                gasBar.SetEntry(gasProto.Name, gasEntry.Amount, gasProto.Color, text: localizedName, tooltip: tooltip);
            }

            dataContainer.AddChild(gasBar);
            gasBar.SetPositionFirst();
        }

        private TweenInstance Fade(Color from, Color to)
        {
            return TweenExtensions.Tween(
                    from,
                    to,
                    v => CTabContainer.Modulate = v,
                    0.25f)
                .SetEasing(Easing.OutQuint);
        }

        private void BootupGasInfo()
        {
            _tweenManager?.Play(
                SequentialTweenInstanceBuilder.New()
                    .Append(Fade(Color.White, Color.Transparent))
                    .Append(Fade(Color.Transparent, Color.White))
                    .Build()
            );
        }
    }
}
