using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Tweens;
using Content.Client.UserInterface.Tweens.Builders;
using Content.Client.UserInterface.Tweens.Easers;
using Content.Client.UserInterface.Tweens.Extensions;
using Content.Shared.Atmos;
using Content.Shared.Atmos.Components;
using Content.Shared.Atmos.EntitySystems;
using Content.Shared.Temperature;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Direction = Robust.Shared.Maths.Direction;

namespace Content.Client.Atmos.UI
{
    // Tojo - Hey did anyone else notice this sucks ass?


    [GenerateTypedNameReferences]
    public sealed partial class GasAnalyzerEntry : PanelContainer
    {
        public GasAnalyzerEntry(EntityUid device, string name)
        {
            RobustXamlLoader.Load(this);
            Header.Text = name;
        }

    }
}
