using System;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Range = Robust.Client.UserInterface.Controls.Range;

namespace Content.Client.Atmos.UI
{
    /// <summary>
    /// Client-side UI used to control a canister.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class GasCanisterWindow : FancyWindow
    {
        public event Action? TankEjectButtonPressed;
        public event Action<float>? ReleasePressureSet;
        public event Action<bool>? ReleaseValveOpenButtonPressed;

        public GasCanisterWindow()
        {
            RobustXamlLoader.Load(this);

            ReleaseValveOpenButton.OnPressed += _ => ReleaseValveOpenButtonPressed?.Invoke(ReleaseValveOpenButton.Pressed);

            TankEjectButton.OnPressed += _ => TankEjectButtonPressed?.Invoke();
            ReleasePressureSlider.OnReleased += _ => ReleasePressureSet?.Invoke(ReleasePressureSlider.Value);
            ReleasePressureSlider.OnValueEdit += OnReleasePressureSliderChanged;
            ReleasePressure.OnValueChanged += OnReleasePressureChanged;
        }

        private void OnReleasePressureChanged(FloatSpinBox.FloatSpinBoxEventArgs args)
        {
            var value = Math.Clamp(args.Value, ReleasePressureSlider.MinValue, ReleasePressureSlider.MaxValue);

            ReleasePressureSlider.Value = value;
            ReleasePressureSet?.Invoke(value);
        }

        private void OnReleasePressureSliderChanged(TguiKnob knob)
        {
            ReleasePressure.Value = knob.Value;
        }

        public void SetCanisterLabel(string label)
        {
            Title = label;
        }

        public void SetCanisterPressure(float pressure, float max = 4500f)
        {
            PressureLabel.Text =
                $"{Loc.GetString("comp-gas-canister-ui-pressure", ("pressure", Math.Round(pressure)))}";
            PressureBar.MaxValue = max;
            PressureBar.Value = pressure;
        }

        public void SetPortStatus(bool status)
        {
            if (status)
            {
                PortStatusLabel.TexturePath = "/Textures/Interface/check mark.png";
            }
            else
            {
                PortStatusLabel.TexturePath = "/Textures/Interface/x mark.png";
            }
        }

        public void SetTankLabel(string? label)
        {
            if (label == null)
            {
                TankEjectButton.Disabled = true;
                TankLabelLabel.Text = Loc.GetString("comp-gas-canister-ui-holding-tank-label-empty");
                return;
            }

            TankEjectButton.Disabled = false;
            TankLabelLabel.Text = label;
        }

        public void SetTankPressure(float pressure)
        {
            TankPressureLabel.Text = Loc.GetString("comp-gas-canister-ui-pressure", ("pressure", Math.Round(pressure)));

        }

        public void SetReleasePressureRange(float min, float max)
        {
            ReleasePressureSlider.MinValue = min;
            ReleasePressureSlider.MaxValue = max;
        }

        public void SetReleasePressure(float pressure)
        {
            if (MathHelper.CloseTo(pressure, ReleasePressure.Value))
                return;

            ReleasePressure.Value = pressure;
            ReleasePressureSlider.Value = pressure;
        }

        public void SetReleaseValve(bool valve)
        {
            if (valve)
            {
                ReleaseValveOpenButton.Pressed = true;
                ReleaseValveLabelStatusButton.Text = Loc.GetString("comp-gas-canister-ui-release-valve-open");
            }
            else
            {
                ReleaseValveOpenButton.Pressed = false;
                ReleaseValveLabelStatusButton.Text = Loc.GetString("comp-gas-canister-ui-release-valve-close");
            }
        }
    }
}
