using System;
using System.Collections.Generic;
using System.Globalization;
using Content.Client.Atmos.EntitySystems;
using Content.Client.UserInterface.Controls;
using Content.Shared.Atmos;
using Content.Shared.Atmos.Prototypes;
using Content.Shared.Localizations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Maths;

namespace Content.Client.Atmos.UI
{
    /// <summary>
    /// Client-side UI used to control a gas mixer.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class GasMixerWindow : FancyWindow
    {
        public event Action? ToggleStatusButtonPressed;
        public event Action<GasMixerState>? MixerNodeDataSet;

        public bool NodeOneLastEdited = true;

        public GasMixerState MixerState;

        public GasMixerWindow()
        {
            RobustXamlLoader.Load(this);

            ToggleStatusButton.OnPressed += _ => SetMixerStatus(!MixerState.Enabled);
            ToggleStatusButton.OnPressed += _ => ToggleStatusButtonPressed?.Invoke();

            SetMaxPressureButton.OnPressed += _ =>
            {
                MixerPressureOutputInput.Text = Atmospherics.MaxOutputPressure.ToString(CultureInfo.CurrentCulture);
            };

            MixerNodeOneInput.OnTextEntered += _ =>
            {
                UserInputParser.TryFloat(MixerNodeOneInput.Text, out var result);
                SetNodePercentages(result);
            };
            MixerNodeTwoInput.OnTextEntered += _ =>
            {
                UserInputParser.TryFloat(MixerNodeTwoInput.Text, out var result2);
                result2 = 1 - result2;
                SetNodePercentages(result2);
            };
        }

        private void ExportData()
        {
            MixerState.OutputPressure = UserInputParser.TryFloat(MixerPressureOutputInput.Text, out var parsed) ? parsed : 1.0f;
            MixerState.MixerOneNodePercentage =
                (UserInputParser.TryFloat(MixerNodeOneInput.Text, out var result) ? result : 1.0f) / 100;
            MixerNodeDataSet?.Invoke(MixerState);
        }

        public void SetOutputPressure(float pressure)
        {
            MixerPressureOutputInput.Text = pressure.ToString(CultureInfo.CurrentCulture);
        }

        public void SetNodePercentages(float nodeOne)
        {
            nodeOne = float.Clamp(nodeOne, 0,1);
            MixerNodeOneInput.Text = nodeOne.ToString("0.##", CultureInfo.CurrentCulture);


            float nodeTwo = 1.0f - nodeOne;
            MixerNodeTwoInput.Text = nodeTwo.ToString("0.##", CultureInfo.CurrentCulture);
        }

        public void SetMixerStatus(bool enabled)
        {
            MixerState.Enabled = enabled;
            ToggleStatusButton.Pressed = enabled;
            if (enabled)
            {
                ToggleStatusLabel.Text = Loc.GetString("comp-gas-mixer-ui-status-enabled");
            }
            else
            {
                ToggleStatusLabel.Text = Loc.GetString("comp-gas-mixer-ui-status-disabled");
            }
        }
    }
}
