using System.Globalization;
using Content.Client.UserInterface.Controls;
using Content.Shared.Atmos;
using Content.Shared.Localizations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Atmos.UI
{
    /// <summary>
    /// Client-side UI used to control a gas pressure pump.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class GasPressurePumpWindow : FancyWindow
    {
        public bool PumpStatus = true;

        public event Action? ToggleStatusButtonPressed;
        public event Action<float>? PumpOutputPressureChanged;

        public float MaxPressure
        {
            get => _maxPressure;
            set
            {
                _maxPressure = value;
                var val = (UserInputParser.TryFloat(PumpPressureOutputInput.Text, out var result) ? result : 1.0f);
                PumpPressureOutputInput.Text = MathF.Min(value, val).ToString(CultureInfo.CurrentCulture);
            }
        }

        private float _maxPressure = Atmospherics.MaxOutputPressure;

        public GasPressurePumpWindow()
        {
            RobustXamlLoader.Load(this);

            ToggleStatusButton.OnPressed += _ => SetPumpStatus(!PumpStatus);
            ToggleStatusButton.OnPressed += _ => ToggleStatusButtonPressed?.Invoke();

            PumpPressureOutputInput.OnTextEntered += _ =>
            {
                var val = (UserInputParser.TryFloat(PumpPressureOutputInput.Text, out var result) ? result : 1.0f);
                val = Math.Clamp(val, 0f, _maxPressure);
                PumpPressureOutputInput.Text = val.ToString(CultureInfo.CurrentCulture);
                PumpOutputPressureChanged?.Invoke(val);
            };

            SetMaxPressureButton.OnPressed += _ =>
            {
                PumpPressureOutputInput.Text = _maxPressure.ToString(CultureInfo.CurrentCulture);
            };
        }

        public void SetOutputPressure(float pressure)
        {
            PumpPressureOutputInput.Text = pressure.ToString(CultureInfo.CurrentCulture);
        }

        public void SetPumpStatus(bool enabled)
        {
            PumpStatus = enabled;
            if (enabled)
            {
                ToggleStatusLabel.Text = Loc.GetString("comp-gas-pump-ui-status-enabled");
            }
            else
            {
                ToggleStatusLabel.Text = Loc.GetString("comp-gas-pump-ui-status-disabled");
            }
        }
    }
}
