using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client.UserInterface.Systems.InspectionHud.UI;

[GenerateTypedNameReferences]
public sealed partial class InspectionUI : UIWidget
{
    public InspectionUI()
    {
        RobustXamlLoader.Load(this);
    }


}
