using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Controls.ColorPicker;
using Content.Shared.CCVar;
using Content.Shared.Pinpointer;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Pinpointer.UI;

[GenerateTypedNameReferences]
public sealed partial class NavMapBeaconWindow : FancyWindow
{
    [Dependency] private IConfigurationManager _cfgManager = default!;
    private string? _defaultLabel;
    private bool _defaultEnabled;
    private Color _defaultColor;
    private Color _currentColor;
    private ColorPicker? _picker;

    // CCVar.
    private int _maxNameLength;

    public event Action<string?, bool, Color>? OnApplyButtonPressed;

    public NavMapBeaconWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);

        VisibleButton.OnPressed += args => UpdateVisibleButton(args.Button.Pressed);
        LabelLineEdit.OnTextChanged += OnTextChanged;
        PickerOpen.OnPressed += _ =>
        {
            if (_picker != null)
                return;
            _picker = new ColorPicker(_currentColor);
            _picker.OpenCentered();
            _picker.OnSaveColors += OnColorSelected;

            _picker.OnClose += () =>
            {
                _picker?.Dispose();
                _picker = null;
            };
        };

        TryEnableApplyButton();
        ApplyButton.OnPressed += OnApplyPressed;
    }

    private void OnColorSelected(Color obj)
    {
        _currentColor = obj;
        TryEnableApplyButton();
    }

    public void SetEntity(EntityUid uid, NavMapBeaconComponent navMap)
    {
        _defaultLabel = navMap.Text;
        _defaultEnabled = navMap.Enabled;
        _defaultColor = navMap.Color;

        _currentColor = _defaultColor;
        UpdateVisibleButton(navMap.Enabled);
        LabelLineEdit.Text = navMap.Text ?? string.Empty;
    }

    private void UpdateVisibleButton(bool value)
    {
        VisibleButton.Pressed = value;
        VisibleButton.Text = Loc.GetString(value
            ? "nav-beacon-toggle-visible"
            : "nav-beacon-toggle-invisible");

        TryEnableApplyButton();
    }

    private void OnTextChanged(LineEdit.LineEditEventArgs obj)
    {
        if (obj.Text.Length > _maxNameLength)
            obj.Control.Text = obj.Text.Substring(0, _maxNameLength);

        TryEnableApplyButton();
    }

    private void TryEnableApplyButton() =>
        ApplyButton.Disabled = LabelLineEdit.Text == (_defaultLabel ?? string.Empty) &&
                               VisibleButton.Pressed == _defaultEnabled && _currentColor == _defaultColor;

    private void OnApplyPressed(BaseButton.ButtonEventArgs obj)
    {
        _defaultLabel = LabelLineEdit.Text == string.Empty ? null : LabelLineEdit.Text;
        _defaultEnabled = VisibleButton.Pressed;
        OnApplyButtonPressed?.Invoke(_defaultLabel, _defaultEnabled, _currentColor);
        TryEnableApplyButton();
    }
}
